### ISSUE TITLE
when creating a new index entry with dependencies the registry always points to crates.io

### ISSUE THREAD

**Issue by arturoc** [ehuss/cargo-index#1]
In .cargo/config i have:

```toml
[registries.my_registry]
index = "ssh://bitbucket.org/team/my_registry"
```

and calling:

```sh
cargo index add --index /path/to/index --index-url ssh://bitbucket.org/team/my_registry -- --allow-dirty
```

dependencies of the crate that are in the same registry will have their registry set to:

```json
"registry":"https://github.com/rust-lang/crates.io-index"
```

**Comment by ehuss** [comment]
Hm, can you show what the `Cargo.toml` dependencies look like?  I tried with SSH gitbucket host, and it still seems to work for me.

For the dependencies of C → B → A, I have in B:
```toml
[dependencies]
a = {version = "0.1", registry = "my_registry"}
```
and in C:
```toml
[dependencies]
b = {version = "0.1", registry = "my_registry"}
```
